@startuml
participant "student" as Object1
participant "person" as Object2
participant "professor" as Object3
participant "course" as Object4
Main -> Object1: <module>()
Object1 -> Object2: <module>()
Object2 -> Object2: Person()
Object2 -> Object1: Student()
Object1 -> Object3: <module>()
Object3 -> Object3: Professor()
Object3 -> Object4: <module>()
Object4 -> Object4: Course()
Object4 -> Object3: __init__()
Object3 -> Object2: __init__()
Object2 -> Object4: __init__()
Object4 -> Object3: assign_to_course()
Object3 -> Object1: __init__()
Object1 -> Object2: __init__()
Object2 -> Object1: __init__()
Object1 -> Object2: __init__()
Object2 -> Object1: enroll()
Object1 -> Object4: add_student()
Object4 -> Object1: enroll()
Object1 -> Object4: add_student()
Object4 -> Object4: list_students()
Object4 -> Object4: <listcomp>()
Object4 -> Object1: list_courses()
Object1 -> Object1: <listcomp>()
@enduml
